version: '3'

services:
  django:
    build: .
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000 && python manage.py collectstatic --no-input"
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
      - ./static:/code/static
    ports:
      - "80:80"
    depends_on:
      - django
